name: Release

on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext
      - name: Compile translations
        run: uv run django-admin compilemessages
        working-directory: easy_maps
      - name: Build package
        run: uv build
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
